"""Phase-5 Secure Autonomous Engineering Substrate contracts."""

from jarvis.engineering_substrate.canonical import (
    SubstrateCanonicalizationError,
    canonical_bytes,
    canonical_digest,
    canonical_payload,
)
from jarvis.engineering_substrate.contracts import (
    SCHEMA_VERSION_V1,
    ArtifactProvenance,
    AttestationStatus,
    CapabilityManifest,
    DependencyArtifact,
    DependencyEcosystem,
    DependencyRequirement,
    DependencyResolution,
    DiscoveryObservation,
    DiscoveryScope,
    DistributionKind,
    HardwareAcceptanceEvidence,
    HardwareAcceptanceRequest,
    HardwareAcceptanceVerdict,
    SandboxFilesystemMode,
    SandboxNetworkMode,
    SandboxProfile,
    SecretDescriptor,
    SecretLease,
    SecretLifecycleState,
    SecretMaterializationMode,
    SourceBuildPolicy,
    VerificationStatus,
)
from jarvis.engineering_substrate.registry import (
    ContractSchemaRegistration,
    ContractSchemaRegistry,
    DuplicateSchemaRegistrationError,
    SubstrateRegistryError,
    UnknownSchemaVersionError,
    default_contract_schema_registry,
)

__all__ = [
    "SCHEMA_VERSION_V1",
    "ArtifactProvenance",
    "AttestationStatus",
    "CapabilityManifest",
    "ContractSchemaRegistration",
    "ContractSchemaRegistry",
    "DependencyArtifact",
    "DependencyEcosystem",
    "DependencyRequirement",
    "DependencyResolution",
    "DiscoveryObservation",
    "DiscoveryScope",
    "DistributionKind",
    "DuplicateSchemaRegistrationError",
    "HardwareAcceptanceEvidence",
    "HardwareAcceptanceRequest",
    "HardwareAcceptanceVerdict",
    "SandboxFilesystemMode",
    "SandboxNetworkMode",
    "SandboxProfile",
    "SecretDescriptor",
    "SecretLease",
    "SecretLifecycleState",
    "SecretMaterializationMode",
    "SourceBuildPolicy",
    "SubstrateCanonicalizationError",
    "SubstrateRegistryError",
    "UnknownSchemaVersionError",
    "VerificationStatus",
    "canonical_bytes",
    "canonical_digest",
    "canonical_payload",
    "default_contract_schema_registry",
]
