"""Governed Phase-8 capability package and lifecycle registry primitives."""

from jarvis.capability_registry.admission import (
    CapabilityPackageAdmissionResult,
    CapabilityPackageAdmissionService,
)
from jarvis.capability_registry.authority import (
    AuthorizedCapabilityLifecycle,
    CapabilityLifecycleAction,
    CapabilityLifecycleAuthorizationError,
    CapabilityLifecycleAuthorityBridge,
    CapabilityLifecycleAuthoritySource,
    CapabilityLifecycleProposalBinding,
)
from jarvis.capability_registry.compatibility import (
    CapabilityCompatibilityEvaluator,
    CapabilityCompatibilityReportV1,
    CompatibilityReason,
    CompatibilityVerdict,
    current_platform_tags,
)
from jarvis.capability_registry.contracts import (
    CAPABILITY_PACKAGE_SCHEMA_URI_V1,
    CAPABILITY_PACKAGE_SCHEMA_VERSION_V1,
    CAPABILITY_RUNTIME_API_ID,
    CAPABILITY_RUNTIME_API_VERSION_V1,
    CapabilityPackageContractError,
    CapabilityPackageKind,
    CapabilityPackageV1,
    PackageArtifactDescriptorV1,
    StrictSemVer,
    parse_capability_package_v1,
)
from jarvis.capability_registry.lifecycle import (
    CapabilityLifecycleMutationError,
    CapabilityLifecycleMutationResult,
    CapabilityLifecyclePreconditionError,
    CapabilityLifecycleReconciliationError,
    CapabilityLifecycleService,
)
from jarvis.capability_registry.migration_runner import (
    CapabilityRegistryMigration,
    CapabilityRegistryMigrationError,
    CapabilityRegistryMigrationIntegrityError,
    CapabilityRegistryMigrationRunner,
    CapabilityRegistrySchemaTooNewError,
    discover_capability_registry_migrations,
)
from jarvis.capability_registry.models import (
    AdmittedCapabilityPackage,
    CapabilityLifecycleEvent,
    CapabilityLifecycleEventKind,
    CapabilityRegistryState,
    DesiredActivationState,
    PackageDisposition,
)
from jarvis.capability_registry.projection import (
    CapabilityEffectiveSnapshot,
    CapabilityInventoryEntry,
    CapabilityManagementMode,
    CapabilityRegistryProjection,
    CapabilitySelfModelProjection,
    CapabilityTransitionFence,
    EffectiveCapabilityState,
    package_component_id,
)
from jarvis.capability_registry.provider import (
    CapabilityHealthProbe,
    CapabilityProviderRegistration,
    CapabilityProviderRegistry,
    CapabilityProviderRegistryError,
    DuplicateCapabilityProviderError,
    UnknownCapabilityProviderError,
)
from jarvis.capability_registry.reconciliation import (
    CapabilityHealthBridge,
    CapabilityLifecycleReconciler,
    PeriodicCapabilityReconciler,
    ReconciliationTrigger,
)
from jarvis.capability_registry.retention import (
    CapabilityArtifactRetentionError,
    CapabilityArtifactRetentionPlanner,
)
from jarvis.capability_registry.schema import (
    capability_package_v1_json_schema,
    capability_package_v1_schema_digest,
)
from jarvis.capability_registry.source import (
    PACKAGE_DIRECTORY_NAME,
    CapabilityPackageSource,
    CapabilityPackageSourceError,
    ReleaseCapabilityPackageSource,
    SourcedCapabilityPackage,
)
from jarvis.capability_registry.store import (
    CapabilityRegistryIntegrityError,
    CapabilityRegistrySelectionError,
    CapabilityRegistryStore,
    CapabilityRegistryStoreError,
    PackageVersionReuseConflict,
    StaleRegistryGenerationError,
    UnknownCapabilityPackageError,
    UnknownManagedCapabilityError,
    default_capability_registry_path,
    default_capability_registry_state_dir,
)

__all__ = [
    "CAPABILITY_PACKAGE_SCHEMA_URI_V1",
    "CAPABILITY_PACKAGE_SCHEMA_VERSION_V1",
    "CAPABILITY_RUNTIME_API_ID",
    "CAPABILITY_RUNTIME_API_VERSION_V1",
    "PACKAGE_DIRECTORY_NAME",
    "AdmittedCapabilityPackage",
    "AuthorizedCapabilityLifecycle",
    "CapabilityArtifactRetentionError",
    "CapabilityArtifactRetentionPlanner",
    "CapabilityLifecycleAction",
    "CapabilityLifecycleAuthorizationError",
    "CapabilityLifecycleAuthorityBridge",
    "CapabilityLifecycleAuthoritySource",
    "CapabilityCompatibilityEvaluator",
    "CapabilityCompatibilityReportV1",
    "CapabilityEffectiveSnapshot",
    "CapabilityHealthBridge",
    "CapabilityHealthProbe",
    "CapabilityInventoryEntry",
    "CapabilityLifecycleEvent",
    "CapabilityLifecycleEventKind",
    "CapabilityLifecycleMutationError",
    "CapabilityLifecycleMutationResult",
    "CapabilityLifecyclePreconditionError",
    "CapabilityLifecycleProposalBinding",
    "CapabilityLifecycleReconciliationError",
    "CapabilityLifecycleService",
    "CapabilityLifecycleReconciler",
    "CapabilityManagementMode",
    "CapabilityPackageAdmissionResult",
    "CapabilityPackageAdmissionService",
    "CapabilityPackageContractError",
    "CapabilityPackageKind",
    "CapabilityPackageSource",
    "CapabilityPackageSourceError",
    "CapabilityPackageV1",
    "CapabilityProviderRegistration",
    "CapabilityProviderRegistry",
    "CapabilityProviderRegistryError",
    "CapabilityRegistryIntegrityError",
    "CapabilityRegistryMigration",
    "CapabilityRegistryMigrationError",
    "CapabilityRegistryMigrationIntegrityError",
    "CapabilityRegistryMigrationRunner",
    "CapabilityRegistryProjection",
    "CapabilityRegistrySchemaTooNewError",
    "CapabilityRegistrySelectionError",
    "CapabilityRegistryState",
    "CapabilityRegistryStore",
    "CapabilityRegistryStoreError",
    "CapabilitySelfModelProjection",
    "CapabilityTransitionFence",
    "CompatibilityReason",
    "CompatibilityVerdict",
    "DesiredActivationState",
    "DuplicateCapabilityProviderError",
    "EffectiveCapabilityState",
    "PackageArtifactDescriptorV1",
    "PackageDisposition",
    "PackageVersionReuseConflict",
    "PeriodicCapabilityReconciler",
    "ReconciliationTrigger",
    "ReleaseCapabilityPackageSource",
    "SourcedCapabilityPackage",
    "StaleRegistryGenerationError",
    "StrictSemVer",
    "UnknownCapabilityPackageError",
    "UnknownCapabilityProviderError",
    "UnknownManagedCapabilityError",
    "capability_package_v1_json_schema",
    "capability_package_v1_schema_digest",
    "current_platform_tags",
    "default_capability_registry_path",
    "default_capability_registry_state_dir",
    "discover_capability_registry_migrations",
    "package_component_id",
    "parse_capability_package_v1",
]
