"""Shared bounded shutdown timing for durable JARVIS work."""

from __future__ import annotations

DBOS_WORKFLOW_DRAIN_TIMEOUT_SECONDS = 70
SUPERVISOR_GRACE_MARGIN_SECONDS = 15
SUPERVISOR_GRACEFUL_SHUTDOWN_TIMEOUT_SECONDS = (
    DBOS_WORKFLOW_DRAIN_TIMEOUT_SECONDS + SUPERVISOR_GRACE_MARGIN_SECONDS
)
SUPERVISOR_SIGNAL_SHUTDOWN_TIMEOUT_SECONDS = 10
