"""Provider/model-neutral routing substrate for JARVIS background engineering work."""

from jarvis.model_routing.models import (
    BenchmarkStatus,
    CostProfile,
    EligibilitySnapshot,
    EvidenceSizeClass,
    LocalityRequirement,
    ModelLocality,
    ModelTarget,
    PrivacyClass,
    ResponseContractResult,
    RoutingAttempt,
    RoutingAttemptKind,
    RoutingDecision,
    RoutingOutcome,
    RoutingRequest,
    RoutingStrategyResult,
    TargetExclusion,
)
from jarvis.model_routing.registry import (
    DuplicateRegistrationError,
    ModelAdapter,
    ModelAdapterRegistry,
    ModelTargetRegistry,
    RoutingRegistryError,
    RoutingStrategy,
    RoutingStrategyRegistry,
    UnknownModelAdapterError,
    UnknownModelTargetError,
    UnknownRoutingStrategyError,
)

__all__ = [
    "BenchmarkStatus",
    "CostProfile",
    "DuplicateRegistrationError",
    "EligibilitySnapshot",
    "EvidenceSizeClass",
    "LocalityRequirement",
    "ModelAdapter",
    "ModelAdapterRegistry",
    "ModelLocality",
    "ModelTarget",
    "ModelTargetRegistry",
    "PrivacyClass",
    "ResponseContractResult",
    "RoutingAttempt",
    "RoutingAttemptKind",
    "RoutingDecision",
    "RoutingOutcome",
    "RoutingRegistryError",
    "RoutingRequest",
    "RoutingStrategy",
    "RoutingStrategyRegistry",
    "RoutingStrategyResult",
    "TargetExclusion",
    "UnknownModelAdapterError",
    "UnknownModelTargetError",
    "UnknownRoutingStrategyError",
]
