"""Provider/model-neutral routing substrate for JARVIS background engineering work."""

from jarvis.model_routing.eligibility import (
    EligibilityPolicy,
    EligibilityReason,
    EligibilityResult,
    EligibilityRuntimeState,
    EligibleTargets,
    IneligibleStrategyTargetError,
    NoEligibleTargets,
    TargetHealthEligibility,
)
from jarvis.model_routing.health import (
    HealthAction,
    HealthMutation,
    TargetHealthRecord,
    apply_provider_failure,
)
from jarvis.model_routing.models import (
    BenchmarkStatus,
    CostProfile,
    EligibilitySnapshot,
    EvidenceSizeClass,
    LocalityRequirement,
    ModelLocality,
    ModelTarget,
    PrivacyClass,
    ResponseContractResult,
    RoutingAttempt,
    RoutingAttemptKind,
    RoutingDecision,
    RoutingOutcome,
    RoutingRequest,
    RoutingStrategyResult,
    TargetExclusion,
)
from jarvis.model_routing.store import (
    ModelRoutingStore,
    PersistedRoutingDecision,
    RoutingStoreError,
)
from jarvis.model_routing.registry import (
    DuplicateRegistrationError,
    ModelAdapter,
    ModelAdapterRegistry,
    ModelTargetRegistry,
    RoutingRegistryError,
    RoutingStrategy,
    RoutingStrategyRegistry,
    UnknownModelAdapterError,
    UnknownModelTargetError,
    UnknownRoutingStrategyError,
)

__all__ = [
    "BenchmarkStatus",
    "CostProfile",
    "DuplicateRegistrationError",
    "EligibilityPolicy",
    "EligibilityReason",
    "EligibilityResult",
    "EligibilityRuntimeState",
    "EligibilitySnapshot",
    "EligibleTargets",
    "EvidenceSizeClass",
    "HealthAction",
    "HealthMutation",
    "IneligibleStrategyTargetError",
    "LocalityRequirement",
    "ModelAdapter",
    "ModelAdapterRegistry",
    "ModelLocality",
    "ModelRoutingStore",
    "ModelTarget",
    "ModelTargetRegistry",
    "NoEligibleTargets",
    "PersistedRoutingDecision",
    "PrivacyClass",
    "ResponseContractResult",
    "RoutingAttempt",
    "RoutingAttemptKind",
    "RoutingDecision",
    "RoutingOutcome",
    "RoutingRegistryError",
    "RoutingRequest",
    "RoutingStoreError",
    "RoutingStrategy",
    "RoutingStrategyRegistry",
    "RoutingStrategyResult",
    "TargetExclusion",
    "TargetHealthEligibility",
    "TargetHealthRecord",
    "UnknownModelAdapterError",
    "UnknownModelTargetError",
    "UnknownRoutingStrategyError",
    "apply_provider_failure",
]
