"""Version-controlled hierarchical Self Model for the accepted JARVIS runtime."""

from __future__ import annotations

from jarvis.self_model.models import (
    ComponentDescriptor,
    DependencyCriticality,
    DependencyDescriptor,
)
from jarvis.self_model.registry import SelfModelRegistry


def build_default_self_model() -> SelfModelRegistry:
    C = ComponentDescriptor
    components = (
        C(
            "jarvis",
            "Whole JARVIS operational architecture and governed product boundary.",
            ("src/jarvis/__init__.py",),
            docs=(
                "docs/CURRENT_ARCHITECTURE.md",
                "docs/PRODUCT.md",
                "docs/ROADMAP.md",
            ),
        ),
        C(
            "engineering.governance",
            "Repository product intent, roadmap, quality gates and dependency metadata.",
            (
                "docs/PRODUCT.md",
                "docs/ROADMAP.md",
                "docs/QUALITY_GATES.md",
                "pyproject.toml",
            ),
            parent_component_id="jarvis",
            docs=(
                "docs/PRODUCT.md",
                "docs/ROADMAP.md",
                "docs/QUALITY_GATES.md",
            ),
        ),
        C(
            "engineering.validation",
            "Repository-wide automated validation and Windows integration gates.",
            (
                ".github/workflows/code-quality.yml",
                ".github/workflows/step4-self-knowledge-sbom.yml",
                ".github/workflows/step4-sqlcipher-417-windows.yml",
                "tests",
            ),
            parent_component_id="jarvis",
            docs=("docs/QUALITY_GATES.md",),
        ),
        C(
            "runtime.core",
            "Process bootstrap, configuration, preflight and core conversation lifecycle.",
            (
                "src/jarvis/__init__.py",
                "src/jarvis/__main__.py",
                "src/jarvis/app.py",
                "src/jarvis/config.py",
                "src/jarvis/conversation.py",
                "src/jarvis/dev_control.py",
                "src/jarvis/dev_supervisor.py",
                "src/jarvis/health_adapters.py",
                "src/jarvis/logging_config.py",
                "src/jarvis/machine_config.py",
                "src/jarvis/preflight.py",
                "src/jarvis/setup.py",
            ),
            parent_component_id="jarvis",
            logger_prefixes=("jarvis",),
            docs=("docs/CURRENT_ARCHITECTURE.md",),
        ),
        C(
            "runtime.voice",
            "Production voice and session runtime.",
            ("src/jarvis/voice",),
            parent_component_id="jarvis",
            health_surface=True,
            product_capabilities=("CAP-001", "CAP-002", "CAP-003"),
            health_probes=("startup_preflight", "session_lifecycle"),
            logger_prefixes=("jarvis.voice", "livekit"),
            docs=("docs/CURRENT_ARCHITECTURE.md",),
        ),
        C(
            "voice.wake",
            "Local wake-word proposal and exact verification cascade.",
            ("src/jarvis/voice/wakeword.py",),
            parent_component_id="runtime.voice",
            tests=("tests/test_voice_runtime.py",),
            logger_prefixes=("jarvis.voice.wakeword",),
        ),
        C(
            "voice.audio",
            "Physical audio routing, MediaDevices processing and playback diagnostics.",
            (
                "src/jarvis/voice/audio.py",
                "src/jarvis/voice/media_devices_audio.py",
                "src/jarvis/voice/observed_audio.py",
                "src/jarvis/voice/paired_audio.py",
                "src/jarvis/voice/silent_audio_recovery.py",
            ),
            parent_component_id="runtime.voice",
            logger_prefixes=(
                "jarvis.voice.audio",
                "jarvis.voice.media_devices_audio",
                "jarvis.voice.silent_audio_recovery",
            ),
        ),
        C(
            "voice.session",
            "Canonical LiveKit realtime session and accepted USER-turn bridge.",
            (
                "src/jarvis/voice/livekit_session.py",
                "src/jarvis/voice/canonical_active_speaker_runtime.py",
                "src/jarvis/voice/context_adapter.py",
                "src/jarvis/voice/context_sync.py",
            ),
            parent_component_id="runtime.voice",
            tests=(
                "tests/test_livekit_session.py",
                "tests/test_canonical_user_activity.py",
            ),
            logger_prefixes=(
                "jarvis.voice.livekit_session",
                "jarvis.voice.canonical_active_speaker_runtime",
            ),
        ),
        C(
            "voice.lifecycle",
            "Wake-to-conversation-to-standby lifecycle and deterministic system speech.",
            (
                "src/jarvis/voice/runtime.py",
                "src/jarvis/voice/standby_tools.py",
                "src/jarvis/voice/startup_greeting.py",
                "src/jarvis/voice/scripted_speech.py",
                "src/jarvis/voice/local_status_speech.py",
            ),
            parent_component_id="runtime.voice",
            tests=("tests/test_semantic_standby.py", "tests/test_voice_runtime.py"),
            logger_prefixes=("jarvis.voice.runtime", "jarvis.voice.scripted_speech"),
        ),
        C(
            "voice.speaker_shadow",
            "Diagnostic enrolled-speaker shadow scoring with no authority effect.",
            (
                "src/jarvis/identity/speaker_shadow.py",
                "src/jarvis/identity/speaker_turn.py",
                "src/jarvis/identity/speaker_identity.py",
            ),
            parent_component_id="runtime.voice",
            logger_prefixes=(
                "jarvis.identity.speaker_shadow",
                "jarvis.voice.canonical_active_speaker_runtime",
            ),
        ),
        C(
            "voice.active_speaker",
            "LR-ASD active-speaker diagnostic shadow using canonical audio and vision evidence.",
            (
                "src/jarvis/identity/active_speaker.py",
                "src/jarvis/identity/lr_asd_model.py",
            ),
            parent_component_id="runtime.voice",
            logger_prefixes=("jarvis.identity.active_speaker",),
        ),
        C(
            "runtime.provider",
            "Cloud AI provider boundary and provider resilience.",
            (
                "src/jarvis/ai_provider.py",
                "src/jarvis/provider_cli.py",
                "src/jarvis/provider_resilience.py",
                "src/jarvis/voice/provider_resilience.py",
            ),
            parent_component_id="jarvis",
            health_surface=True,
            product_capabilities=("CAP-048", "CAP-049"),
            health_probes=("provider_credential", "provider_session"),
            logger_prefixes=(
                "jarvis.provider_resilience",
                "jarvis.voice.provider_resilience",
                "livekit.plugins.google",
                "google_genai",
            ),
        ),
        C(
            "provider.realtime",
            "Realtime conversational model/session provider surface.",
            (
                "src/jarvis/voice/production_runtime.py",
                "src/jarvis/voice/agent.py",
            ),
            parent_component_id="runtime.provider",
            logger_prefixes=(
                "jarvis.voice.production_runtime",
                "livekit.plugins.google",
            ),
        ),
        C(
            "provider.planner",
            "Provider-backed semantic planning used by governed JARVIS Hands.",
            (
                "src/jarvis/hands/planner.py",
                "src/jarvis/hands/provider_adapters.py",
            ),
            parent_component_id="runtime.provider",
            logger_prefixes=("jarvis.hands.planner", "jarvis.hands.provider_adapters"),
        ),
        C(
            "provider.tts",
            "Scripted/lifecycle text-to-speech provider path.",
            (
                "src/jarvis/voice/scripted_speech.py",
                "src/jarvis/voice/startup_greeting.py",
                "src/jarvis/voice/local_status_speech.py",
            ),
            parent_component_id="runtime.provider",
            logger_prefixes=("jarvis.voice.scripted_speech",),
        ),
        C(
            "provider.resilience",
            "Deterministic provider failure classification and bounded survival behavior.",
            (
                "src/jarvis/provider_resilience.py",
                "src/jarvis/voice/provider_resilience.py",
            ),
            parent_component_id="runtime.provider",
            tests=("tests/test_provider_resilience.py",),
            logger_prefixes=(
                "jarvis.provider_resilience",
                "jarvis.voice.provider_resilience",
            ),
        ),
        C(
            "vision.base",
            "Camera perception and tracking foundation.",
            ("src/jarvis/vision",),
            parent_component_id="jarvis",
            health_surface=True,
            health_probes=("vision_capture", "vision_inference"),
            logger_prefixes=("jarvis.vision",),
        ),
        C(
            "vision.perception",
            "Camera capture, RF-DETR person detection, head association and OC-SORT tracking.",
            (
                "src/jarvis/vision/camera.py",
                "src/jarvis/vision/detector.py",
                "src/jarvis/vision/tracker.py",
                "src/jarvis/vision/head.py",
                "src/jarvis/vision/head_mediapipe.py",
                "src/jarvis/vision/service.py",
            ),
            parent_component_id="vision.base",
            logger_prefixes=("jarvis.vision.service", "jarvis.vision.diagnostics"),
        ),
        C(
            "vision.owner_reacquisition",
            "Fresh OWNER loss/re-entry confirmation and target reacquisition state.",
            (
                "src/jarvis/vision/owner_reacquisition.py",
                "src/jarvis/vision/targeting.py",
                "src/jarvis/vision/framing.py",
            ),
            parent_component_id="vision.base",
            logger_prefixes=("jarvis.vision.owner_reacquisition",),
        ),
        C(
            "vision.pocket3",
            "Pocket 3 native tracking transport and evidence.",
            (
                "src/jarvis/vision/native_owner_tracking.py",
                "src/jarvis/vision/pocket3_native.py",
                "src/jarvis/vision/pocket3_recovery.py",
            ),
            parent_component_id="vision.base",
            health_surface=True,
            health_probes=("pocket_ble", "pocket_wifi", "native_lock_evidence"),
            logger_prefixes=(
                "jarvis.vision.native_owner_tracking",
                "jarvis.vision.pocket3_native",
                "jarvis.vision.pocket3_recovery",
            ),
        ),
        C(
            "pocket3.transport",
            "Pocket 3 BLE/Wi-Fi/DUML transport, pairing, ACK and RX liveness.",
            (
                "src/jarvis/vision/pocket3_native.py",
                "src/jarvis/vision/pocket3_recovery.py",
            ),
            parent_component_id="vision.pocket3",
            tests=(
                "tests/test_pocket3_ble_startup_readiness.py",
                "tests/test_pocket3_transport_liveness.py",
                "tests/test_pocket3_transport_watchdog.py",
            ),
            logger_prefixes=(
                "jarvis.vision.pocket3_native",
                "jarvis.vision.pocket3_recovery",
            ),
        ),
        C(
            "pocket3.tracking",
            "Native A6 OWNER target control and A5/0x89 tracking evidence.",
            ("src/jarvis/vision/native_owner_tracking.py",),
            parent_component_id="vision.pocket3",
            tests=("tests/test_native_owner_tracking.py",),
            logger_prefixes=("jarvis.vision.native_owner_tracking",),
        ),
        C(
            "identity",
            "Owner identity, presence, liveness and speaker evidence foundation.",
            ("src/jarvis/identity",),
            parent_component_id="jarvis",
            logger_prefixes=("jarvis.identity",),
        ),
        C(
            "identity.owner",
            "OWNER face template, context, evidence and enrollment lifecycle.",
            (
                "src/jarvis/identity/owner_context.py",
                "src/jarvis/identity/owner_evidence.py",
                "src/jarvis/identity/owner_template_runtime.py",
                "src/jarvis/identity/owner_enrollment.py",
                "src/jarvis/identity/face_template.py",
            ),
            parent_component_id="identity",
            logger_prefixes=("jarvis.identity.owner",),
        ),
        C(
            "identity.liveness",
            "Face/liveness/PAD evidence used only within accepted trust boundaries.",
            (
                "src/jarvis/identity/liveness.py",
                "src/jarvis/identity/passive_liveness.py",
                "src/jarvis/identity/passive_pad.py",
            ),
            parent_component_id="identity",
            logger_prefixes=("jarvis.identity.liveness",),
        ),
        C(
            "identity.speaker",
            "Speaker enrollment, templates and diagnostic speaker evidence.",
            (
                "src/jarvis/identity/speaker_enrollment.py",
                "src/jarvis/identity/speaker_template.py",
                "src/jarvis/identity/speaker_shadow.py",
            ),
            parent_component_id="identity",
            logger_prefixes=("jarvis.identity.speaker",),
        ),
        C(
            "memory",
            "Canonical durable and live-context memory foundation.",
            ("src/jarvis/memory",),
            parent_component_id="jarvis",
            logger_prefixes=("jarvis.memory",),
        ),
        C(
            "memory.conversation",
            "Canonical conversation/live-context memory coordination.",
            (
                "src/jarvis/memory/live_context.py",
                "src/jarvis/memory/context.py",
                "src/jarvis/memory/runtime.py",
            ),
            parent_component_id="memory",
            logger_prefixes=("jarvis.memory.live_context", "jarvis.memory.runtime"),
        ),
        C(
            "memory.durable",
            "SQLCipher/SQLite durable memory lifecycle and migrations.",
            (
                "src/jarvis/memory/database.py",
                "src/jarvis/memory/service.py",
                "src/jarvis/memory/migration_runner.py",
                "src/jarvis/memory/migrations",
            ),
            parent_component_id="memory",
            resources=("encrypted memory database",),
            logger_prefixes=("jarvis.memory.database", "jarvis.memory.service"),
        ),
        C(
            "memory.retrieval",
            "Bounded memory query, retrieval, evidence and release-gating pipeline.",
            (
                "src/jarvis/memory/query.py",
                "src/jarvis/memory/query_coordinator.py",
                "src/jarvis/memory/retrieval.py",
                "src/jarvis/memory/evidence_gate.py",
                "src/jarvis/memory/release_guard.py",
            ),
            parent_component_id="memory",
            logger_prefixes=("jarvis.memory.query", "jarvis.memory.retrieval"),
        ),
        C(
            "memory.candidates",
            "Session-local implicit memory candidate extraction and quarantine.",
            (
                "src/jarvis/memory/candidates.py",
                "src/jarvis/memory/candidate_runtime.py",
                "src/jarvis/memory/extractors.py",
            ),
            parent_component_id="memory",
            logger_prefixes=("jarvis.memory.candidate_runtime",),
        ),
        C(
            "authority",
            "Policy, approval, permit and security-audit boundary.",
            ("src/jarvis/authority", "src/jarvis/security"),
            parent_component_id="jarvis",
            health_surface=True,
            product_capabilities=("CAP-034", "CAP-035", "CAP-036"),
            health_probes=("authority_tool_readiness", "audit_persistence"),
            logger_prefixes=("jarvis.authority", "jarvis.security"),
        ),
        C(
            "authority.policy",
            "Deterministic risk floor and fail-closed OPA policy evaluation.",
            (
                "src/jarvis/authority/risk.py",
                "src/jarvis/authority/policy.py",
                "src/jarvis/authority/local_opa.py",
            ),
            parent_component_id="authority",
            logger_prefixes=("jarvis.authority.policy", "jarvis.authority.local_opa"),
        ),
        C(
            "authority.verification",
            "Approval, Windows Hello/T3 verification and one-time permit issuance.",
            (
                "src/jarvis/authority/approval.py",
                "src/jarvis/authority/strong_approval.py",
                "src/jarvis/authority/verifier.py",
                "src/jarvis/authority/permit.py",
                "src/jarvis/security/dpapi.py",
                "tools/windows/Jarvis.WindowsHelloVerifier",
            ),
            parent_component_id="authority",
            logger_prefixes=("jarvis.authority", "jarvis.security.dpapi"),
        ),
        C(
            "authority.audit",
            "Privacy-aware immutable action and result audit evidence.",
            (
                "src/jarvis/authority/audit.py",
                "src/jarvis/authority/evidence.py",
                "src/jarvis/authority/proposal.py",
            ),
            parent_component_id="authority",
            logger_prefixes=("jarvis.authority.audit",),
        ),
        C(
            "capability_runtime",
            "Capability discovery and governed execution runtime.",
            ("src/jarvis/capabilities",),
            parent_component_id="jarvis",
            health_surface=True,
            product_capabilities=("CAP-018", "CAP-021", "CAP-022", "CAP-032"),
            health_probes=("capability_catalog",),
            logger_prefixes=("jarvis.capabilities",),
        ),
        C(
            "capability.discovery",
            "Provider-neutral capability sources, catalog refresh and semantic resolution.",
            (
                "src/jarvis/capabilities/discovery.py",
                "src/jarvis/capabilities/models.py",
                "src/jarvis/capabilities/execution.py",
            ),
            parent_component_id="capability_runtime",
            logger_prefixes=("jarvis.capabilities.discovery",),
        ),
        C(
            "capability.local_reads",
            "Approved-root project/system/document and Self-Awareness reads.",
            (
                "src/jarvis/capabilities/local_reads.py",
                "src/jarvis/capabilities/system_reads.py",
                "src/jarvis/capabilities/document_reader.py",
                "src/jarvis/capabilities/self_awareness_reads.py",
            ),
            parent_component_id="capability_runtime",
            capability_keys=("local:self_awareness.read",),
            logger_prefixes=("jarvis.capabilities",),
        ),
        C(
            "capability.windows",
            "Typed Windows device, app, audio, media and session capabilities.",
            (
                "src/jarvis/capabilities/windows_control.py",
                "src/jarvis/capabilities/windows_devices.py",
                "src/jarvis/capabilities/windows_native.py",
                "src/jarvis/capabilities/windows_focus.py",
            ),
            parent_component_id="capability_runtime",
            logger_prefixes=("jarvis.capabilities.windows",),
        ),
        C(
            "hands",
            "Computer, browser, file and device execution foundation.",
            ("src/jarvis/hands", "src/jarvis/computer"),
            parent_component_id="jarvis",
            health_surface=True,
            product_capabilities=("CAP-023", "CAP-024", "CAP-025", "CAP-026"),
            health_probes=("hands_executor_availability",),
            logger_prefixes=("jarvis.hands", "jarvis.computer"),
        ),
        C(
            "hands.orchestrator",
            "Canonical goal grounding, planning, execution, observation and replanning.",
            (
                "src/jarvis/hands/orchestrator.py",
                "src/jarvis/hands/grounding.py",
                "src/jarvis/hands/workflow.py",
                "src/jarvis/voice/hands_orchestrator.py",
                "src/jarvis/voice/hands_latency_tool.py",
            ),
            parent_component_id="hands",
            logger_prefixes=("jarvis.hands.orchestrator", "jarvis.voice.hands"),
        ),
        C(
            "hands.native",
            "Native structured Windows execution and postcondition verification.",
            (
                "src/jarvis/computer/structured_windows.py",
                "src/jarvis/capabilities/windows_native.py",
                "src/jarvis/capabilities/windows_devices.py",
            ),
            parent_component_id="hands",
            logger_prefixes=("jarvis.computer", "jarvis.capabilities.windows"),
        ),
        C(
            "hands.desktop",
            "Structured desktop UI Automation and governed visual fallback.",
            (
                "src/jarvis/capabilities/window_scoped_computer.py",
                "src/jarvis/capabilities/visual_desktop.py",
                "src/jarvis/computer/executor.py",
            ),
            parent_component_id="hands",
            logger_prefixes=("jarvis.computer", "jarvis.capabilities.visual_desktop"),
        ),
        C(
            "hands.browser",
            "Playwright browser execution surface.",
            ("src/jarvis/capabilities/browser_playwright.py",),
            parent_component_id="hands",
            logger_prefixes=("jarvis.capabilities.browser_playwright",),
        ),
        C(
            "hands.files",
            "Governed file/document reads and writes within approved roots.",
            (
                "src/jarvis/capabilities/local_reads.py",
                "src/jarvis/capabilities/local_writes.py",
                "src/jarvis/capabilities/document_edits.py",
                "src/jarvis/capabilities/document_reader.py",
            ),
            parent_component_id="hands",
            logger_prefixes=(
                "jarvis.capabilities.local",
                "jarvis.capabilities.document",
            ),
        ),
        C(
            "hands.development",
            "Bounded Git/development operations without arbitrary shell authority.",
            ("src/jarvis/capabilities/development_git.py",),
            parent_component_id="hands",
            logger_prefixes=("jarvis.capabilities.development_git",),
        ),
        C(
            "knowledge.research",
            "Provider-neutral source-aware current web research with provenance.",
            ("src/jarvis/knowledge", "src/jarvis/voice/research_tools.py"),
            parent_component_id="jarvis",
            logger_prefixes=("jarvis.knowledge", "jarvis.voice.research_tools"),
        ),
        C(
            "sensors",
            "Hardware/media sensor discovery and experimental GStreamer probe surfaces.",
            ("src/jarvis/sensors",),
            parent_component_id="jarvis",
            logger_prefixes=("jarvis.sensors",),
        ),
        C(
            "observability",
            "Operational correlation, structured events, traces and metrics.",
            ("src/jarvis/observability", "src/jarvis/logging_config.py"),
            parent_component_id="jarvis",
            health_surface=True,
            product_capabilities=("CAP-037", "CAP-038"),
            health_probes=("local_log_spool", "telemetry_export"),
            logger_prefixes=("jarvis.observability",),
        ),
        C(
            "observability.logs",
            "Bounded structured JSONL logging, correlation and sensitive-data redaction.",
            (
                "src/jarvis/observability/logging.py",
                "src/jarvis/observability/redaction.py",
                "src/jarvis/observability/context.py",
                "src/jarvis/observability/events.py",
                "src/jarvis/observability/evidence_query.py",
            ),
            parent_component_id="observability",
            resources=("%LOCALAPPDATA%/JARVIS/logs/jarvis.jsonl",),
            logger_prefixes=("jarvis",),
        ),
        C(
            "observability.telemetry",
            "Backend-neutral OpenTelemetry traces and metrics with export disabled by default.",
            ("src/jarvis/observability/telemetry.py",),
            parent_component_id="observability",
            logger_prefixes=("jarvis.observability.telemetry",),
        ),
        C(
            "incidents",
            "Operational incident records and durable engineering memory.",
            ("src/jarvis/incidents",),
            parent_component_id="jarvis",
            health_surface=True,
            product_capabilities=("CAP-038", "CAP-046"),
            health_probes=("incident_store",),
            resources=("%LOCALAPPDATA%/JARVIS/operations/incidents.sqlite3",),
            logger_prefixes=("jarvis.incidents",),
        ),
        C(
            "incidents.store",
            "SQLite engineering incident/evidence persistence and resolved-fix history.",
            (
                "src/jarvis/incidents/store.py",
                "src/jarvis/incidents/service.py",
                "src/jarvis/incidents/models.py",
            ),
            parent_component_id="incidents",
            resources=("%LOCALAPPDATA%/JARVIS/operations/incidents.sqlite3",),
            logger_prefixes=("jarvis.incidents",),
        ),
        C(
            "self_awareness",
            "Composition of Self Model, health registry, operational evidence and incidents.",
            ("src/jarvis/self_awareness.py", "src/jarvis/self_model"),
            parent_component_id="jarvis",
            logger_prefixes=("jarvis.self_awareness",),
            docs=(
                "docs/decisions/ADR-018_SELF_AWARENESS_EVIDENCE_AND_HEALTH_FOUNDATION.md",
            ),
        ),
        C(
            "performance",
            "Runtime CPU/RAM/thread/GPU profiling and accepted performance diagnostics.",
            ("src/jarvis/performance",),
            parent_component_id="jarvis",
            logger_prefixes=("jarvis.performance",),
        ),
    )

    dependencies = (
        DependencyDescriptor(
            "runtime.voice",
            "runtime.provider",
            criticality=DependencyCriticality.BLOCKING,
        ),
        DependencyDescriptor(
            "runtime.voice",
            "capability_runtime",
            criticality=DependencyCriticality.DEGRADING,
        ),
        DependencyDescriptor(
            "voice.session",
            "provider.realtime",
            criticality=DependencyCriticality.BLOCKING,
        ),
        DependencyDescriptor(
            "voice.active_speaker",
            "vision.base",
            criticality=DependencyCriticality.DEGRADING,
        ),
        DependencyDescriptor(
            "vision.pocket3",
            "vision.base",
            criticality=DependencyCriticality.BLOCKING,
        ),
        DependencyDescriptor(
            "pocket3.tracking",
            "pocket3.transport",
            criticality=DependencyCriticality.BLOCKING,
        ),
        DependencyDescriptor(
            "identity.owner",
            "vision.base",
            criticality=DependencyCriticality.DEGRADING,
        ),
        DependencyDescriptor(
            "memory.candidates",
            "runtime.provider",
            criticality=DependencyCriticality.OPTIONAL,
        ),
        DependencyDescriptor(
            "capability_runtime",
            "authority",
            criticality=DependencyCriticality.BLOCKING,
        ),
        DependencyDescriptor(
            "hands",
            "capability_runtime",
            criticality=DependencyCriticality.BLOCKING,
        ),
        DependencyDescriptor(
            "hands.orchestrator",
            "authority",
            criticality=DependencyCriticality.BLOCKING,
        ),
        DependencyDescriptor(
            "hands.orchestrator",
            "provider.planner",
            criticality=DependencyCriticality.DEGRADING,
        ),
        DependencyDescriptor(
            "knowledge.research",
            "runtime.provider",
            criticality=DependencyCriticality.DEGRADING,
        ),
        DependencyDescriptor(
            "incidents",
            "observability",
            criticality=DependencyCriticality.DEGRADING,
        ),
        DependencyDescriptor(
            "self_awareness",
            "observability",
            criticality=DependencyCriticality.DEGRADING,
        ),
        DependencyDescriptor(
            "self_awareness",
            "incidents",
            criticality=DependencyCriticality.DEGRADING,
        ),
    )
    return SelfModelRegistry(components=components, dependencies=dependencies)
